[versions]
# Application
versionName = "2.2.0"
versionCode = "52"

# SDK
minSdk = "26"
targetSdk = "35"
compileSdk = "35"

# Gradle
gradle = "8.8.0"

# Kotlin
kotlin = "2.1.0"

# KotlinX
kotlinxCoroutines = "1.7.3"
kotlinxDatetime = "0.6.1"
kotlinxSerializationJson = "1.7.3"
kotlinxImmutable = "0.3.7"

# KMP
kmpCompose = "1.7.3"
kmpComplete = "1.1.0"
kmpSwiftKlib = "0.6.3"
kmpLifecycle = "2.8.4"
kmpNavigation = "2.8.0-alpha11"
kmpPaging = "3.3.0-alpha02-0.5.1"
mokoPermissions = "0.18.0"
mokoBiometry = "0.4.0"
calf = "0.5.5"

# AndroidX
androidxCore = "1.15.0"
androidxCoreSplash = "1.0.1"
androidxAppCompat = "1.7.0"
androidxActivity = "1.10.0"
androidxFragment = "1.8.5"
androidxPreference = "1.2.1"
androidxDataStore = "1.1.2"
androidxPalette = "1.0.0"
androidxAnnotation = "1.9.1"
androidxMedia3 = "1.5.1"
androidxCompose = "2025.01.00"

# Google
playReview = "2.0.2"
playUpdate = "2.1.0"
playServiceAds = "23.6.0"
playServiceOss = "17.1.0"
material = "1.12.0"
accompanist = "0.33.2-alpha"
ksp = "2.1.0-1.0.29"
gms = "4.4.2"

# Billing
billing = "6.1.0"

# koin
koin = "4.0.0"

# matsumo
fankt = "0.0.8"

# Others
ktor = "3.0.1"
coil3 = "3.0.4"
ksoup = "0.1.2"
composeWebView = "1.9.40-alpha03"
composeRichEditor = "1.0.0-rc10"
autolink = "1.1.1"
windowSize = "0.3.2"
reveal = "3.1.1"
detekt = "1.23.7"
libraries = "11.2.3"
buildKonfig = "0.15.1"
cupertino = "0.1.0-alpha04"
twitterComposeRule = "0.0.26"

# Debugs
firebase = "33.7.0"
leakCanary = "2.13"
flipper = "0.247.0"
napier = "2.7.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle" }
android-library = { id = "com.android.library", version.ref = "gradle" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
gms = { id = "com.google.gms.google-services", version.ref = "gms" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version = "3.0.2" }
libraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "libraries" }
kmp = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kmpCompose = { id = "org.jetbrains.compose", version.ref = "kmpCompose" }
kmpComplete = { id = "com.louiscad.complete-kotlin", version.ref = "kmpComplete" }
kmpSwiftKlib = { id = "io.github.ttypic.swiftklib", version.ref = "kmpSwiftKlib" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
## Dependency of the include build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "gradle" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
gms-services = { group = "com.google.gms", name = "google-services", version.ref = "gms" }
gms-oss = { group = "com.google.android.gms", name = "oss-licenses-plugin", version = "0.10.6" }
build-konfig-gradlePlugin = { group = "com.codingfeline.buildkonfig", name = "buildkonfig-gradle-plugin", version.ref = "buildKonfig" }
secret-gradlePlugin = { group = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", name = "secrets-gradle-plugin", version = "2.0.1" }
detekt-gradlePlugin = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }

# Kotlin
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }

# KotlinX
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxImmutable" }

# AndroidX
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidxCoreSplash" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidxAnnotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppCompat" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidxActivity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidxFragment" }
androidx-preference = { module = "androidx.preference:preference-ktx", version.ref = "androidxPreference" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "androidxDataStore" }
androidx-datastore-proto = { module = "androidx.datastore:datastore-core", version.ref = "androidxDataStore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidxDataStore" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "androidxMedia3" }
androidx-media3-exoplayer-dashboard = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "androidxMedia3" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "androidxMedia3" }
androidx-media3-session = { module = "androidx.media3:media3-session", version.ref = "androidxMedia3" }

# Compose
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidxCompose" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-binding = { module = "androidx.compose.ui:ui-viewbinding" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

# KMP
kmp-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "kmpLifecycle" }
kmp-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "kmpLifecycle" }
kmp-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "kmpNavigation" }
kmp-paging-common = { module = "app.cash.paging:paging-common", version.ref = "kmpPaging" }
kmp-paging-compose = { module = "app.cash.paging:paging-compose-common", version.ref = "kmpPaging" }

# Billing
billing = { module = "com.android.billingclient:billing", version.ref = "billing" }
billing-ktx = { module = "com.android.billingclient:billing-ktx", version.ref = "billing" }

# MOKO
moko-permissions = { module = "dev.icerock.moko:permissions", version.ref = "mokoPermissions" }
moko-permissions-compose = { module = "dev.icerock.moko:permissions-compose", version.ref = "mokoPermissions" }
moko-biometry = { module = "dev.icerock.moko:biometry", version.ref = "mokoBiometry" }
moko-biometry-compose = { module = "dev.icerock.moko:biometry-compose", version.ref = "mokoBiometry" }
calf-ui = { module = "com.mohamedrejeb.calf:calf-ui", version.ref = "calf" }

# Cupertino
cupertino = { module = "io.github.alexzhirkevich:cupertino", version.ref = "cupertino" }
cupertino-native = { module = "io.github.alexzhirkevich:cupertino-native", version.ref = "cupertino" }
cupertino-adaptive = { module = "io.github.alexzhirkevich:cupertino-adaptive", version.ref = "cupertino" }
cupertino-icons = { module = "io.github.alexzhirkevich:cupertino-icons-extended", version.ref = "cupertino" }

# Google
play-review = { module = "com.google.android.play:review-ktx", version.ref = "playReview" }
play-update = { module = "com.google.android.play:app-update-ktx", version.ref = "playUpdate" }
play-service-oss = { module = "com.google.android.gms:play-services-oss-licenses", version.ref = "playServiceOss" }
play-service-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServiceAds" }
google-material = { module = "com.google.android.material:material", version.ref = "material" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-compose-theme-adapter = { module = "com.google.accompanist:accompanist-themeadapter-material", version.ref = "accompanist" }
accompanist-compose-theme-adapter3 = { module = "com.google.accompanist:accompanist-themeadapter-material3", version.ref = "accompanist" }
accompanist-navigation = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanist" }
accompanist-placeholder-material = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }

# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crushlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging-ktx" }
firebase-appindexing = { module = "com.google.firebase:firebase-appindexing" }
firebase-config = { module = "com.google.firebase:firebase-config-ktx" }
firebase-dynamiclinks = { module = "com.google.firebase:firebase-dynamic-links-ktx" }

# Koin
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core"  }
koin-android = { module = "io.insert-koin:koin-android" }
koin-androidx-startup = { module = "io.insert-koin:koin-androidx-startup", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }

# Ktor
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktot-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

# Reveal
reveal-core = { module = "com.svenjacobs.reveal:reveal-core", version.ref = "reveal" }
reveal-shapes = { module = "com.svenjacobs.reveal:reveal-shapes", version.ref = "reveal" }

# matsumo
fankt-fanbox = { module = "me.matsumo.fankt:fanbox", version.ref = "fankt" }

# Others
coil3-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
coil3-network = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil3" }
coil3-gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coil3" }
ksoup = { module = "com.fleeksoft.ksoup:ksoup", version.ref = "ksoup" }
unifile = { module = "com.github.tachiyomiorg:unifile", version = "17bec43" }
webview-compose = { module = "io.github.kevinnzou:compose-webview-multiplatform", version.ref = "composeWebView" }
rich-editor = { module = "com.mohamedrejeb.richeditor:richeditor-compose", version.ref = "composeRichEditor" }
autolink = { module = "sh.calvin.autolinktext:autolinktext", version.ref = "autolink" }
window-size = { module = "dev.chrisbanes.material3:material3-window-size-class-multiplatform", version.ref = "windowSize" }
desugar = { module = "com.android.tools:desugar_jdk_libs", version = "2.1.4" }
placeholder = { module = "com.eygraber:compose-placeholder-material3", version = "1.0.7" }
libraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "libraries" }
libraries-ui = { module = "com.mikepenz:aboutlibraries-compose", version.ref = "libraries" }

# Debugs
facebook-flipper = { module = "com.facebook.flipper:flipper", version.ref = "flipper" }
facebook-flipper-network = { module = "com.facebook.flipper:flipper-network-plugin", version.ref = "flipper" }
facebook-flipper-leakcanary = { module = "com.facebook.flipper:flipper-leakcanary2-plugin", version.ref = "flipper" }
facebook-soloader = { module = "com.facebook.soloader:soloader", version = "0.10.5" }
facebook-noop = { module = "com.facebook.flipper:flipper-noop", version.ref = "flipper" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanary" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
twitter-compose-rule = { module = "com.twitter.compose.rules:detekt", version.ref = "twitterComposeRule" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[bundles]
infra-api = [
    "kotlin-stdlib",
    "kotlin-reflect",
    "kotlinx-datetime",
    "kotlinx-serialization-json",
    "kotlinx-collections-immutable",
    "napier",
]

ui-android-api = [
    "androidx-core",
    "androidx-annotation",
    "androidx-appcompat",
    "androidx-activity",
    "androidx-activity-compose",
    "androidx-fragment",
    "androidx-compose-runtime",
    "androidx-compose-ui",
    "androidx-compose-ui-binding",
    "accompanist-systemuicontroller",
    "accompanist-compose-theme-adapter",
    "accompanist-compose-theme-adapter3",
    "accompanist-permissions",
    "accompanist-placeholder-material",
    "google-material",
]

ui-common-api = [
    "kmp-lifecycle-runtime-compose",
    "kmp-lifecycle-viewmodel-compose",
    "kmp-navigation-compose",
    "kmp-paging-common",
    "kmp-paging-compose",
    "coil3-compose",
    "coil3-network",
    "coil3-gif",
    "window-size",
    "reveal-core",
    "reveal-shapes",
]

billing = [
    "billing",
    "billing-ktx",
]

firebase = [
    "firebase-analytics",
    "firebase-crushlytics",
    "firebase-messaging",
    "firebase-config",
    "firebase-dynamiclinks",
]

media3 = [
    "androidx-media3-exoplayer",
    "androidx-media3-exoplayer-dashboard",
    "androidx-media3-ui",
    "androidx-media3-session",
]

cupertino = [
    "cupertino",
    "cupertino-native",
    "cupertino-adaptive",
    "cupertino-icons",
]

ktor = [
    "ktor-core",
    "ktor-cio",
    "ktor-content-negotiation",
    "ktor-serialization-json",
    "ktot-logging",
]

koin = [
    "koin-core",
    "koin-compose",
    "koin-compose-viewmodel",
]
